In [59]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [60]:
df = pd.read_csv('train.csv')[['Age','Pclass','Fare','Survived']]

In [61]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [62]:
df.isnull().mean()*100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [63]:
X = df.drop('Survived',axis=1)
y = df['Survived']

In [64]:
X_train,  X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [65]:
X_train.shape, X_test.shape

((712, 3), (179, 3))

In [66]:
from sklearn.impute import KNNImputer
knn = KNNImputer(n_neighbors=3, add_indicator=True)

In [67]:
X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [68]:
lr = LogisticRegression()
lr.fit(X_train_trf,y_train)
y_pred = lr.predict(X_test_trf)
accuracy_score(y_test,y_pred)

0.7597765363128491

In [69]:
# For Try Case to use SimpleImputer

In [70]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(add_indicator=True)

In [71]:
X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [72]:
lr = LogisticRegression()
lr.fit(X_train_trf2,y_train)
y_pred2 = lr.predict(X_test_trf2)
accuracy_score(y_test,y_pred2)

0.7486033519553073